name: Run bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0

      - name: Run a one-line script
        run: python3 antifrz.py ${{ secrets.BOT_EMAIL }} "${{ secrets.BOT_PASSWORD }}"
